# docker-compose.yml
version: '3.8'
services:
  flask:
    image: files-collector
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 5000:5000
    volumes: 
      - type: bind
        source: ./files_collector
        target: /flask-app
    environment:
        FLASK_DEBUG: 1