version: "3.8"
services:
  flask:
      build:
        target: prod
      ports:
        - 1234:8000
      environment:
        FLASK_DEBUG: 0
      volumes:
        - type: volume
          source: data-volume
          target: /home/master
volumes:
  data-volume: